"""Replace paused_time with resume_time

Revision ID: 2547a59058fa
Revises: babd6eeebfae
Create Date: 2018-06-10 14:49:50.249979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2547a59058fa'
down_revision = 'babd6eeebfae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('resume_date', sa.DateTime(), nullable=True))
    op.drop_column('boards', 'paused_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('paused_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('boards', 'resume_date')
    # ### end Alembic commands ###
