"""Added user and board tables

Revision ID: 56cd20e2ede2
Revises: 
Create Date: 2018-06-10 03:47:01.363520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56cd20e2ede2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Unicode(length=25), nullable=False),
    sa.Column('username', sa.Unicode(length=50), nullable=False),
    sa.Column('password', sa.Unicode(length=120), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('boards',
    sa.Column('id', sa.Unicode(length=25), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('resume_date', sa.DateTime(), nullable=True),
    sa.Column('ended_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Unicode(length=10), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('columns', sa.Integer(), nullable=False),
    sa.Column('mines_list', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('last_plays_state', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('result', sa.Unicode(), nullable=True),
    sa.Column('owner_id', sa.Unicode(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boards')
    op.drop_table('users')
    # ### end Alembic commands ###
