"""Add elapsed_time to board

Revision ID: babd6eeebfae
Revises: 56cd20e2ede2
Create Date: 2018-06-10 13:52:03.028036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'babd6eeebfae'
down_revision = '56cd20e2ede2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('elapsed_time', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'elapsed_time')
    # ### end Alembic commands ###
